version: "3.5"
services:
  postgresv2:
    image: postgres:9.3
    container_name: postgresv2
    volumes:
      - postgres-datav2:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  # APP*******************************************************************
  springbootapp:
    image: softplan-api-rest-service-pessoas-v2:latest
    build: ./
    container_name: softplan-api-rest-service-pessoas-v2
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgresv2
    links:
      - postgresv2
volumes:
  postgres-datav2:
